import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import apiClient from "../api/apiClient";
import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";
import GraphViewer from "../components/graph/GraphViewer";

export default function HistoryDetails() {
  const { id } = useParams();
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAnalysis();
  }, []);



  const fetchAnalysis = async () => {
    try {
      const response = await apiClient.get(`/api/history/${id}`);
      console.log("HISTORY ANALYSIS:", response.data.analysis);
      setAnalysis(response.data.analysis);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  if (loading)
    return <div className="text-white text-xl">Loading analysis...</div>;

  if (!analysis)
    return <div className="text-white text-xl">Analysis not found.</div>;


  const isSocialAnalysis = Boolean(
    analysis?.image?.path
  );
  // Text-only analyses show verification/detection only.
  // Social-media screenshot analyses additionally show engagement,
  // spread prediction and propagation graph.


  const imageUrl = (() => {
    const path = analysis.image?.path;

    if (!path) {
      return null;
    }

    const cleanPath = path
      .replace(/\\/g, "/")
      .replace(/^\/+/, "");

    const backendUrl =
      import.meta.env.VITE_API_URL ||
      "https://misinfo-system.onrender.com";

    // --------------------------------------------------------
    // Existing absolute URL
    // --------------------------------------------------------

    if (
      cleanPath.startsWith("http://") ||
      cleanPath.startsWith("https://")
    ) {
      // Convert old/local backend URLs to production backend.
      if (
        cleanPath.includes("127.0.0.1:8000") ||
        cleanPath.includes("localhost:8000")
      ) {
        const uploadsIndex = cleanPath.indexOf("/uploads/");

        if (uploadsIndex !== -1) {
          return (
            backendUrl +
            cleanPath.substring(uploadsIndex)
          );
        }
      }

      return cleanPath;
    }

    // --------------------------------------------------------
    // backend/uploads/filename
    // --------------------------------------------------------

    if (cleanPath.startsWith("backend/uploads/")) {
      return `${backendUrl}/uploads/${cleanPath.substring(
        "backend/uploads/".length
      )}`;
    }

    // --------------------------------------------------------
    // uploads/filename
    // --------------------------------------------------------

    if (cleanPath.startsWith("uploads/")) {
      return `${backendUrl}/${cleanPath}`;
    }

    // --------------------------------------------------------
    // filename only
    // --------------------------------------------------------

    return `${backendUrl}/uploads/${cleanPath}`;
  })();

  const downloadPDF = async () => {
    try {
      const pdf = new jsPDF("p", "mm", "a4");

      let pageWidth = pdf.internal.pageSize.getWidth();
      let pageHeight = pdf.internal.pageSize.getHeight();

      const margin = 15;
      const contentWidth = pageWidth - margin * 2;

      let y = 18;

      const addFooter = () => {
        pdf.setFontSize(8);
        pdf.setTextColor(120);

        pdf.text(
          "Generated by AI Misinformation Analysis System",
          pageWidth / 2,
          pageHeight - 8,
          { align: "center" }
        );

        pdf.setTextColor(0);
      };

      const addPageIfNeeded = (requiredHeight = 20) => {
        if (y + requiredHeight > pageHeight - 18) {
          addFooter();

          pdf.addPage();

          pageWidth = pdf.internal.pageSize.getWidth();
          pageHeight = pdf.internal.pageSize.getHeight();

          y = 18;
        }
      };

      const addSectionTitle = (title) => {
        addPageIfNeeded(15);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(15);
        pdf.setTextColor(25, 45, 75);

        pdf.text(title, margin, y);

        y += 5;

        pdf.setDrawColor(100, 110, 120);

        pdf.line(
          margin,
          y,
          pageWidth - margin,
          y
        );

        y += 8;

        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0);
      };

      const addLabelValue = (label, value) => {
        addPageIfNeeded(10);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(10);

        pdf.text(
          `${label}:`,
          margin,
          y
        );

        pdf.setFont("helvetica", "normal");

        const lines = pdf.splitTextToSize(
          String(value ?? "-"),
          contentWidth - 30
        );

        pdf.text(
          lines,
          margin + 30,
          y
        );

        y += Math.max(
          7,
          lines.length * 5 + 2
        );
      };

      const addTextBlock = (text) => {
        const lines = pdf.splitTextToSize(
          String(text || "-"),
          contentWidth
        );

        for (const line of lines) {
          addPageIfNeeded(6);

          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(10);

          pdf.text(
            line,
            margin,
            y
          );

          y += 5;
        }

        y += 3;
      };

      const addCardRow = (items) => {
        addPageIfNeeded(25);

        const gap = 5;

        const cardWidth =
          (
            contentWidth -
            gap * (items.length - 1)
          ) / items.length;

        const cardHeight = 23;

        items.forEach((item, index) => {
          const x =
            margin +
            index * (cardWidth + gap);

          pdf.setDrawColor(
            210,
            215,
            225
          );

          pdf.setFillColor(
            245,
            247,
            250
          );

          pdf.roundedRect(
            x,
            y,
            cardWidth,
            cardHeight,
            3,
            3,
            "FD"
          );

          pdf.setFontSize(8);
          pdf.setTextColor(100);

          pdf.text(
            item.label,
            x + 5,
            y + 7
          );

          pdf.setFont(
            "helvetica",
            "bold"
          );

          pdf.setFontSize(12);
          pdf.setTextColor(
            20,
            30,
            45
          );

          const valueLines =
            pdf.splitTextToSize(
              String(item.value ?? "-"),
              cardWidth - 10
            );

          pdf.text(
            valueLines,
            x + 5,
            y + 15
          );

          pdf.setFont(
            "helvetica",
            "normal"
          );
        });

        y += cardHeight + 8;
      };


      /* ==========================================
         TITLE
      ========================================== */

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(22);

      pdf.setTextColor(
        20,
        35,
        60
      );

      pdf.text(
        "Analysis Report",
        margin,
        y
      );

      y += 7;

      pdf.setFont(
        "helvetica",
        "normal"
      );

      pdf.setFontSize(10);

      pdf.setTextColor(100);

      pdf.text(
        "Generated by AI Misinformation Analysis System",
        margin,
        y
      );

      y += 12;


      /* ==========================================
         ANALYSIS INFORMATION
      ========================================== */

      addLabelValue(
        "Analysis ID",
        analysis.analysis_id
      );

      if (isSocialAnalysis) {
        addLabelValue(
          "Platform",
          analysis.platform?.platform ||
          "Unknown"
        );
      }

      addLabelValue(
        "Date",
        analysis.analysis_time
          ? new Date(
            analysis.analysis_time
          ).toLocaleString()
          : "-"
      );

      addLabelValue(
        "Processing Time",
        `${analysis.metadata?.processing_time ??
        "-"
        } sec`
      );

      y += 3;


      /* ==========================================
         RESULT SUMMARY
      ========================================== */

      addSectionTitle(
        "Result Summary"
      );

      const summaryCards = [
        {
          label: "Verification",
          value:
            analysis.final_result?.label ||
            "-"
        },
        {
          label: "Confidence",
          value:
            `${analysis.final_result?.confidence ??
            0
            }%`
        },
        {
          label: "Risk Level",
          value:
            analysis.final_result?.risk_level ||
            "-"
        }
      ];

      if (isSocialAnalysis) {
        summaryCards.push({
          label: "Predicted Reach",
          value:
            Number(
              analysis.prediction?.predicted_reach ??
              0
            ).toLocaleString()
        });
      }

      addCardRow(summaryCards);

      /* ==========================================
   ORIGINAL CONTENT
========================================== */

      addSectionTitle("Original Content");

      if (imageUrl) {

        addPageIfNeeded(25);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(11);
        pdf.setTextColor(40, 55, 75);

        pdf.text(
          "Uploaded Evidence",
          margin,
          y
        );

        y += 7;

        try {

          const response =
            await fetch(imageUrl, {
              method: "GET",
              mode: "cors",
              cache: "no-store",
            });

          if (!response.ok) {
            throw new Error(
              `Image request failed: ${response.status}`
            );
          }

          const blob =
            await response.blob();

          if (!blob.size) {
            throw new Error(
              "Uploaded image is empty"
            );
          }

          const imageData =
            await new Promise(
              (resolve, reject) => {

                const reader =
                  new FileReader();

                reader.onload = () =>
                  resolve(reader.result);

                reader.onerror =
                  () =>
                    reject(
                      new Error(
                        "Unable to convert image"
                      )
                    );

                reader.readAsDataURL(blob);
              }
            );

          const image =
            await new Promise(
              (resolve, reject) => {

                const img =
                  new Image();

                img.onload = () =>
                  resolve(img);

                img.onerror =
                  () =>
                    reject(
                      new Error(
                        "Unable to decode uploaded image"
                      )
                    );

                img.src = imageData;
              }
            );

          const imageWidth =
            image.naturalWidth ||
            image.width;

          const imageHeight =
            image.naturalHeight ||
            image.height;

          if (!imageWidth || !imageHeight) {
            throw new Error(
              "Invalid image dimensions"
            );
          }

          const maxWidth =
            contentWidth;

          const maxHeight = 115;

          const ratio =
            imageWidth /
            imageHeight;

          let drawWidth =
            maxWidth;

          let drawHeight =
            drawWidth / ratio;

          if (drawHeight > maxHeight) {

            drawHeight =
              maxHeight;

            drawWidth =
              drawHeight * ratio;
          }

          addPageIfNeeded(
            drawHeight + 15
          );

          const imageX =
            margin +
            (contentWidth -
              drawWidth) / 2;

          /*
           * Let jsPDF detect PNG/JPEG from
           * the data URL instead of forcing JPEG.
           */
          pdf.addImage(
            imageData,
            imageX,
            y,
            drawWidth,
            drawHeight
          );

          y +=
            drawHeight + 12;

        } catch (error) {

          console.error(
            "PDF IMAGE ERROR:",
            error
          );

          pdf.setFontSize(9);
          pdf.setTextColor(180, 50, 50);

          pdf.text(
            "Uploaded image could not be embedded.",
            margin,
            y
          );

          pdf.setTextColor(0);

          y += 10;
        }
      }

      /*
       * IMPORTANT:
       * Do NOT print OCR / vision extracted text.
       */
      if (analysis.text?.trim()) {

        addPageIfNeeded(15);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(11);
        pdf.setTextColor(40, 55, 75);

        pdf.text(
          imageUrl
            ? "Original Text"
            : "Submitted Text",
          margin,
          y
        );

        y += 7;

        addTextBlock(
          analysis.text
        );
      }

      /* ==========================================
         FACT VERIFICATION
      ========================================== */

      addSectionTitle(
        "Fact Verification"
      );

      addLabelValue(
        "Verdict",
        analysis.fact_verification?.verdict
      );

      addLabelValue(
        "Reason",
        analysis.fact_verification?.reason
      );


      /* ==========================================
         AI DETECTION
      ========================================== */

      addSectionTitle(
        "AI Detection"
      );

      addLabelValue(
        "Detected Claim",
        analysis.detection?.claim
      );

      addLabelValue(
        "Prediction",
        analysis.detection?.prediction
      );

      if (
        analysis.detection
          ?.manipulation_signals
          ?.length
      ) {

        addLabelValue(
          "Manipulation Indicators",
          analysis.detection.manipulation_signals.join(
            ", "
          )
        );
      }


      /* ==========================================
   ENGAGEMENT
========================================== */

      if (isSocialAnalysis) {

        addSectionTitle(
          "Engagement Metrics"
        );

        addCardRow([
          {
            label: "Likes",
            value:
              analysis.engagement?.likes ??
              0
          },
          {
            label: "Comments",
            value:
              analysis.engagement?.comments ??
              0
          },
          {
            label: "Shares",
            value:
              analysis.engagement?.shares ??
              0
          },
          {
            label: "Reposts",
            value:
              analysis.engagement?.reposts ??
              0
          }
        ]);

        addCardRow([
          {
            label: "Bookmarks",
            value:
              analysis.engagement?.bookmarks ??
              0
          },
          {
            label: "Followers",
            value:
              analysis.engagement?.followers ??
              0
          }
        ]);

      }


      if (isSocialAnalysis) {

        /* ==========================================
         SPREAD PREDICTION
      ========================================== */

        addSectionTitle(
          "Spread Prediction"
        );

        addCardRow([
          {
            label: "Predicted Reach",
            value:
              Number(
                analysis.prediction?.predicted_reach ??
                0
              ).toLocaleString()
          },
          {
            label: "Spread Probability",
            value:
              `${analysis.prediction?.spread_probability ??
              0
              }%`
          },
          {
            label: "Virality Score",
            value:
              `${analysis.prediction?.virality_score ??
              0
              }%`
          },
          {
            label: "Risk Level",
            value:
              analysis.prediction?.risk_level ||
              "-"
          }
        ]);
      }

      /* ==========================================
         PLATFORM
      ========================================== */

      if (isSocialAnalysis) {

        addSectionTitle(
          "Platform Information"
        );

        addCardRow([
          {
            label: "Platform",
            value:
              analysis.platform?.platform ||
              "Unknown"
          },
          {
            label: "Confidence",
            value:
              `${analysis.platform?.confidence ??
              100
              }%`
          }
        ]);

      }
      if (isSocialAnalysis) {

        /* ==========================================
         PROPAGATION GRAPH
      ========================================== */

        addSectionTitle(
          "Propagation Network"
        );

        addLabelValue(
          "Nodes",
          analysis.graph?.nodes?.length ?? 0
        );

        addLabelValue(
          "Edges",
          analysis.graph?.edges?.length ?? 0
        );

        addLabelValue(
          "Platform",
          analysis.platform?.platform || "-"
        );

        const graphWrapper =
          document.getElementById(
            "pdf-graph-container"
          );

        const graphContainer =
          graphWrapper?.querySelector(
            "#graph-container"
          );

        if (graphContainer) {

          try {

            // Give React Flow enough time to finish
            // rendering and fit the complete graph.
            await new Promise(
              resolve =>
                setTimeout(resolve, 1800)
            );

            const graphImage =
              await toPng(
                graphContainer,
                {
                  cacheBust: true,
                  pixelRatio: 2,
                  backgroundColor: "#1e293b",

                  width:
                    graphContainer.clientWidth,

                  height:
                    graphContainer.clientHeight,

                  style: {
                    width:
                      `${graphContainer.clientWidth}px`,

                    height:
                      `${graphContainer.clientHeight}px`,
                  },
                }
              );

            const graphImg =
              await new Promise(
                (resolve, reject) => {

                  const img =
                    new Image();

                  img.onload = () =>
                    resolve(img);

                  img.onerror = reject;

                  img.src = graphImage;
                }
              );

            /*
             * ==========================================
             * LANDSCAPE GRAPH PAGE
             * ==========================================
             */

            pdf.addPage(
              "a4",
              "landscape"
            );

            const landscapeWidth =
              pdf.internal.pageSize.getWidth();

            const landscapeHeight =
              pdf.internal.pageSize.getHeight();

            const graphMargin = 12;

            /*
             * Title
             */

            pdf.setFont(
              "helvetica",
              "bold"
            );

            pdf.setFontSize(20);

            pdf.setTextColor(
              25,
              45,
              75
            );

            pdf.text(
              "Propagation Network",
              graphMargin,
              16
            );

            /*
             * Statistics
             */

            pdf.setFont(
              "helvetica",
              "normal"
            );

            pdf.setFontSize(10);

            pdf.setTextColor(
              90
            );

            pdf.text(
              `Nodes: ${analysis.graph?.nodes?.length ?? 0
              }`,
              graphMargin,
              25
            );

            pdf.text(
              `Edges: ${analysis.graph?.edges?.length ?? 0
              }`,
              graphMargin + 45,
              25
            );

            pdf.text(
              `Platform: ${analysis.platform?.platform || "-"
              }`,
              graphMargin + 90,
              25
            );

            /*
             * ==========================================
             * AVAILABLE GRAPH AREA
             * ==========================================
             */

            const availableWidth =
              landscapeWidth -
              graphMargin * 2;

            const availableHeight =
              landscapeHeight -
              40;

            const graphRatio =
              graphImg.width /
              graphImg.height;

            let graphWidth =
              availableWidth;

            let graphHeight =
              graphWidth /
              graphRatio;

            /*
             * Never allow graph to exceed
             * the available page height.
             */

            if (
              graphHeight >
              availableHeight
            ) {

              graphHeight =
                availableHeight;

              graphWidth =
                graphHeight *
                graphRatio;
            }

            /*
             * Center horizontally.
             */

            const graphX =
              graphMargin +
              (
                availableWidth -
                graphWidth
              ) / 2;

            /*
             * Center vertically.
             */

            const graphY =
              32 +
              (
                availableHeight -
                graphHeight
              ) / 2;

            /*
             * Graph border
             */

            pdf.setDrawColor(
              190,
              195,
              205
            );

            pdf.roundedRect(
              graphX - 2,
              graphY - 2,
              graphWidth + 4,
              graphHeight + 4,
              2,
              2
            );

            /*
             * FULL GRAPH
             */

            pdf.addImage(
              graphImage,
              "PNG",
              graphX,
              graphY,
              graphWidth,
              graphHeight
            );

            /*
             * Footer
             */

            pdf.setFontSize(8);

            pdf.setTextColor(
              120
            );

            pdf.text(
              "Generated by AI Misinformation Analysis System",
              landscapeWidth / 2,
              landscapeHeight - 7,
              {
                align: "center",
              }
            );

          } catch (graphError) {

            console.error(
              "GRAPH PDF ERROR:",
              graphError
            );

            pdf.setFontSize(10);

            pdf.setTextColor(
              180,
              50,
              50
            );

            pdf.text(
              "Propagation graph could not be embedded.",
              margin,
              y
            );
          }
        }

      }

      /* ==========================================
         SAVE
      ========================================== */

      pdf.save(
        `analysis_${analysis.analysis_id}.pdf`
      );

    } catch (error) {

      console.error(
        "PDF GENERATION ERROR:",
        error
      );

      alert(
        "Unable to generate the PDF report."
      );
    }
  };

  return (
    <div className="space-y-6 text-white">

      <div className="space-y-8">

        <div className="bg-slate-800 rounded-3xl border border-slate-700 p-8">

          <div className="flex flex-col lg:flex-row justify-between gap-8">

            <div>

              <h1 className="text-5xl font-bold text-white">
                Analysis Report
              </h1>

              <p className="text-slate-400 mt-3 text-lg">
                Generated by AI Misinformation Analysis System
              </p>

              <div className="grid grid-cols-2 gap-x-10 gap-y-3 mt-8 text-sm">

                <div>
                  <span className="text-slate-500">
                    Analysis ID
                  </span>

                  <p className="text-white font-medium">
                    {analysis.analysis_id}
                  </p>
                </div>

                {isSocialAnalysis && (
                  <div>
                    <span className="text-slate-500">
                      Platform
                    </span>

                    <p className="text-white font-medium">
                      {analysis.platform?.platform || "Unknown"}
                    </p>
                  </div>
                )}

                <div>
                  <span className="text-slate-500">
                    Date
                  </span>

                  <p className="text-white font-medium">
                    {new Date(
                      analysis.analysis_time
                    ).toLocaleString()}
                  </p>
                </div>

                <div>
                  <span className="text-slate-500">
                    Processing Time
                  </span>

                  <p className="text-white font-medium">
                    {analysis.metadata?.processing_time ?? "-"} sec
                  </p>
                </div>

              </div>

            </div>

            <button
              onClick={downloadPDF}
              className="self-start lg:self-center bg-blue-600 hover:bg-blue-700 transition px-8 py-4 rounded-2xl font-semibold text-lg"
            >
              Export PDF Report
            </button>

          </div>

        </div>

        <div
          className={`grid grid-cols-2 ${isSocialAnalysis ? "xl:grid-cols-4" : "xl:grid-cols-3"
            } gap-6`}
        >

          <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">
            <p className="text-slate-400">
              Verification
            </p>

            <h2 className="text-4xl font-bold text-green-400 mt-2">
              {analysis.final_result?.label}
            </h2>
          </div>

          <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">
            <p className="text-slate-400">
              Confidence
            </p>

            <h2 className="text-4xl font-bold text-blue-400 mt-2">
              {analysis.final_result?.confidence}%
            </h2>
          </div>

          <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">
            <p className="text-slate-400">
              Risk Level
            </p>

            <h2 className="text-4xl font-bold text-red-400 mt-2">
              {analysis.final_result?.risk_level}
            </h2>
          </div>

          {isSocialAnalysis && (
            <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">
              <p className="text-slate-400">
                Predicted Reach
              </p>

              <h2 className="text-4xl font-bold text-cyan-400 mt-2">
                {Number(
                  analysis.prediction?.predicted_reach || 0
                ).toLocaleString()}
              </h2>
            </div>
          )}

        </div>

      </div>

      <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

        <h2 className="text-2xl font-bold text-white mb-6">
          Original Content
        </h2>

        {imageUrl && analysis.text?.trim() && (
          <div className="grid lg:grid-cols-2 gap-6">

            <div>

              <h3 className="text-lg font-semibold text-slate-300 mb-4">
                Uploaded Evidence
              </h3>

              <div className="bg-slate-900 rounded-xl border border-slate-700 overflow-hidden">
                <img
                  src={imageUrl}
                  alt="Uploaded evidence"
                  className="w-full max-h-[500px] object-contain"
                />
              </div>

            </div>

            <div>

              <h3 className="text-lg font-semibold text-slate-300 mb-4">
                Original Text
              </h3>

              <div className="bg-slate-900 rounded-xl border border-slate-700 p-6 max-h-[500px] overflow-y-auto">

                <p className="text-slate-300 leading-8 whitespace-pre-wrap">
                  {analysis.text}
                </p>

              </div>

            </div>

          </div>
        )}

        {imageUrl && !analysis.text?.trim() && (
          <div>

            <h3 className="text-lg font-semibold text-slate-300 mb-4">
              Uploaded Evidence
            </h3>

            <div className="bg-slate-900 rounded-xl border border-slate-700 overflow-hidden flex justify-center">

              <img
                src={imageUrl}
                alt="Uploaded evidence"
                className="max-w-full max-h-[650px] object-contain"
              />

            </div>

          </div>
        )}

        {!imageUrl && analysis.text?.trim()?.trim() && (
          <div>

            <h3 className="text-lg font-semibold text-slate-300 mb-4">
              Original Text
            </h3>

            <div className="bg-slate-900 rounded-xl border border-slate-700 p-6 max-h-[500px] overflow-y-auto">

              <p className="text-slate-300 leading-8 whitespace-pre-wrap">
                {analysis.text}
              </p>

            </div>

          </div>
        )}

      </div>

      <div className="grid lg:grid-cols-2 gap-6">

        <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

          <h2 className="text-2xl font-bold text-white mb-5">
            Fact Verification
          </h2>

          <div className="space-y-5">

            <div>

              <p className="text-slate-400 text-sm">
                Verdict
              </p>

              <p className="text-xl font-semibold text-green-400 mt-1">
                {analysis.fact_verification?.verdict || "-"}
              </p>

            </div>

            <div>

              <p className="text-slate-400 text-sm">
                Reason
              </p>

              <div className="mt-2 max-h-48 overflow-y-auto pr-2">

                <p className="text-slate-300 leading-7">
                  {analysis.fact_verification?.reason || "-"}
                </p>

              </div>

            </div>

          </div>

        </div>

        <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

          <h2 className="text-2xl font-bold text-white mb-5">
            AI Detection
          </h2>

          <div className="space-y-4">

            <div>

              <p className="text-slate-400 text-sm">
                Detected Claim
              </p>

              <p className="text-slate-300 mt-1">
                {analysis.detection?.claim || "-"}
              </p>

            </div>

            <div>

              <p className="text-slate-400 text-sm">
                Prediction
              </p>

              <p className="text-slate-300 mt-1">
                {analysis.detection?.prediction || "-"}
              </p>

            </div>

            {analysis.detection?.manipulation_signals?.length > 0 && (
              <div>

                <p className="text-slate-400 text-sm mb-3">
                  Manipulation Indicators
                </p>

                <div className="flex flex-wrap gap-2">

                  {analysis.detection.manipulation_signals.map(
                    signal => (
                      <span
                        key={signal}
                        className="px-4 py-2 rounded-full bg-blue-600/20 border border-blue-500 text-blue-300 text-sm"
                      >
                        {signal}
                      </span>
                    )
                  )}

                </div>

              </div>
            )}

          </div>

        </div>

      </div>

      {isSocialAnalysis && (
        <div className="grid lg:grid-cols-2 gap-6">

          <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

            <h2 className="text-2xl font-bold text-white mb-6">
              Engagement Metrics
            </h2>

            <div className="grid grid-cols-2 gap-4">

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Likes
                </p>

                <h3 className="text-2xl font-bold text-pink-400 mt-2">
                  {analysis.engagement?.likes ?? 0}
                </h3>
              </div>

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Comments
                </p>

                <h3 className="text-2xl font-bold text-blue-400 mt-2">
                  {analysis.engagement?.comments ?? 0}
                </h3>
              </div>

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Shares
                </p>

                <h3 className="text-2xl font-bold text-green-400 mt-2">
                  {analysis.engagement?.shares ?? 0}
                </h3>
              </div>

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Reposts
                </p>

                <h3 className="text-2xl font-bold text-orange-400 mt-2">
                  {analysis.engagement?.reposts ?? 0}
                </h3>
              </div>

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Bookmarks
                </p>

                <h3 className="text-2xl font-bold text-yellow-400 mt-2">
                  {analysis.engagement?.bookmarks ?? 0}
                </h3>
              </div>

              <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                <p className="text-slate-400 text-sm">
                  Followers
                </p>

                <h3 className="text-2xl font-bold text-cyan-400 mt-2">
                  {analysis.engagement?.followers ?? 0}
                </h3>
              </div>

            </div>

          </div>

          <div className="space-y-6">

            <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

              <h2 className="text-2xl font-bold text-white mb-6">
                Spread Prediction
              </h2>

              <div className="grid grid-cols-2 gap-4">

                <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                  <p className="text-slate-400 text-sm">
                    Reach
                  </p>

                  <h3 className="text-2xl font-bold text-cyan-400 mt-2">
                    {Number(
                      analysis.prediction?.predicted_reach ?? 0
                    ).toLocaleString()}
                  </h3>
                </div>

                <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                  <p className="text-slate-400 text-sm">
                    Probability
                  </p>

                  <h3 className="text-2xl font-bold text-blue-400 mt-2">
                    {analysis.prediction?.spread_probability ?? 0}%
                  </h3>
                </div>

                <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                  <p className="text-slate-400 text-sm">
                    Virality
                  </p>

                  <h3 className="text-2xl font-bold text-purple-400 mt-2">
                    {analysis.prediction?.virality_score ?? 0}%
                  </h3>
                </div>

                <div className="bg-slate-900 rounded-xl p-5 border border-slate-700 h-28">
                  <p className="text-slate-400 text-sm">
                    Risk Level
                  </p>

                  <h3 className="text-2xl font-bold text-red-400 mt-2">
                    {analysis.prediction?.risk_level || "-"}
                  </h3>
                </div>

              </div>

            </div>

            <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6">

              <h2 className="text-2xl font-bold text-white mb-5">
                Platform Information
              </h2>

              <div className="grid grid-cols-2 gap-4">

                <div>
                  <p className="text-slate-400 text-sm">
                    Platform
                  </p>

                  <p className="text-white text-xl font-semibold mt-2">
                    {analysis.platform?.platform || "Unknown"}
                  </p>
                </div>

                <div>
                  <p className="text-slate-400 text-sm">
                    Confidence
                  </p>

                  <p className="text-white text-xl font-semibold mt-2">
                    {analysis.platform?.confidence ?? 100}%
                  </p>
                </div>

              </div>

            </div>

          </div>

        </div>
      )}



      {isSocialAnalysis && (
        <div className="bg-slate-800 rounded-2xl border border-slate-700 overflow-hidden">

          <div className="flex items-center justify-between px-8 py-6 border-b border-slate-700">

            <div>

              <h2 className="text-3xl font-bold text-white">
                Propagation Network
              </h2>

              <p className="text-slate-400 mt-2">
                AI-generated misinformation propagation graph.
              </p>

            </div>

            <div className="flex gap-6 text-sm">

              <div className="text-center">

                <p className="text-slate-400">
                  Nodes
                </p>

                <p className="text-2xl font-bold text-blue-400">
                  {analysis.graph?.nodes?.length ?? 0}
                </p>

              </div>

              <div className="text-center">

                <p className="text-slate-400">
                  Edges
                </p>

                <p className="text-2xl font-bold text-green-400">
                  {analysis.graph?.edges?.length ?? 0}
                </p>

              </div>

              <div className="text-center">

                <p className="text-slate-400">
                  Platform
                </p>

                <p className="text-xl font-semibold text-cyan-400">
                  {analysis.platform?.platform}
                </p>

              </div>

            </div>

          </div>

          <div className="p-6">

            <div
              id="pdf-graph-container"
              className="rounded-xl overflow-hidden border border-slate-700"
              style={{
                height: "560px",
                width: "100%",
              }}
            >
              <GraphViewer
                analysis={analysis}
                graph={analysis.graph}
                interactive={false}
                pdfMode={true}
                showControls={false}
                graphHeight="560px"
              />
            </div>

          </div>

        </div>
      )}

    </div>
  );
}